spring.application.name=qmd
# 1. Le indica a Hibernate que cree o actualice las tablas automáticamente basado en tus entidades
spring.jpa.hibernate.ddl-auto=update

# 2. Obliga a Spring Boot a esperar a que Hibernate cree las tablas ANTES de correr el data.sql
spring.jpa.defer-datasource-initialization=true